# Generated by Django 5.1.2 on 2024-11-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('ign', models.CharField(db_column='IGN', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('role', models.CharField(db_column='Role', max_length=100)),
            ],
            options={
                'db_table': 'Player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Team',
                'managed': False,
            },
        ),
    ]
