# Generated by Django 5.1.2 on 2024-11-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('player_ign', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Login',
                'managed': False,
            },
        ),
    ]
