# Generated by Django 5.1.2 on 2024-12-06 23:46

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=255, primary_key=True)),
                ('team_name', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(db_column='Game_ID', max_length=255, primary_key=True)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('genre', models.CharField(db_column='Genre', max_length=100)),
            ],
            options={
                'db_table': 'Game',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('ign', models.CharField(db_column='IGN', max_length=255, primary_key=True)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('role', models.CharField(db_column='Role', max_length=100)),
                ('team', models.ForeignKey(db_column='Team_ID', on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
            options={
                'db_table': 'Player',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.CharField(db_column='Match_ID', max_length=255, primary_key=True)),
                ('match_name', models.CharField(blank=True, db_column='Match_Name', max_length=255, null=True)),
                ('match_date', models.DateField(db_column='Match_Date')),
                ('match_time', models.TimeField(db_column='Match_Time')),
                ('game', models.ForeignKey(db_column='Game_ID', on_delete=django.db.models.deletion.CASCADE, to='api.game')),
                ('team', models.ForeignKey(db_column='Team_ID', on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
            options={
                'db_table': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='MatchStatistics',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True)),
                ('team_score', models.IntegerField(db_column='Team_Score', default=0)),
                ('enemy_score', models.IntegerField(db_column='Enemy_Score', default=0)),
                ('result', models.CharField(db_column='Result', max_length=10)),
                ('first_blood', models.BooleanField(db_column='First_Blood', default=False)),
                ('kills', models.IntegerField(db_column='Kills', default=0)),
                ('deaths', models.IntegerField(db_column='Deaths', default=0)),
                ('assists', models.IntegerField(db_column='Assists', default=0)),
                ('playtime', models.TimeField(db_column='Playtime')),
                ('match', models.ForeignKey(db_column='Match_ID', on_delete=django.db.models.deletion.CASCADE, to='api.matches')),
                ('player', models.ForeignKey(db_column='Player_IGN', on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
            options={
                'db_table': 'Match_Statistics',
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('screenshot_id', models.CharField(db_column='Screenshot_ID', max_length=255, primary_key=True)),
                ('screenshot_data', models.BinaryField(db_column='Screenshot_Data')),
                ('note', models.TextField(blank=True, db_column='Note', null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_column='Upload_Date')),
                ('match', models.ForeignKey(db_column='Match_ID', on_delete=django.db.models.deletion.CASCADE, to='api.matches')),
            ],
            options={
                'db_table': 'Screenshot',
            },
        ),
    ]
