# Generated by Django 5.1.2 on 2024-11-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('ign', models.CharField(db_column='IGN', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('role', models.CharField(db_column='Role', max_length=100)),
            ],
            options={
                'db_table': 'Player',
                'managed': False,
            },
        ),
    ]
