# Generated by Django 5.1.2 on 2024-12-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_matchstatistics_first_blood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchstatistics',
            name='first_blood',
            field=models.IntegerField(default=0),
        ),
    ]
